### PR TITLE
fix: resolve merge conflicts causing 28 TypeScript compilation errors…

### LINKED ISSUE #3081: BUG: Backend fails to compile — 28 TypeScript errors from unresolved merge conflicts in 5 files
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

unning `npx tsc --noEmit` in the `backend/` directory fails with 28 TypeScript
errors across 5 files. The errors are caused by unresolved merge conflicts that
left duplicate/broken code blocks in service files and config files.

### Steps to reproduce

```bash
git clone https://github.com/ronisarkarexe/story-spark-ai
cd story-spark-ai/backend
npx tsc --noEmit
```

### Environment (if relevant)

_No response_

### Screenshots or screen recording (if helpful)

_No response_

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

### PR DESCRIPTION
**Pull request by rishita510**
… across 5 files

## Before you open this PR

- **Issue:** closes #3081
- **Description:** 
Resolves unresolved merge conflicts in 5 backend service/config files that 
caused 28 TypeScript compilation errors, breaking the entire backend build.
Fixed by restoring clean function bodies and removing duplicate/orphaned 
code blocks left behind from bad merges.
- **Screenshots:** Add screenshots or a short recording when they help (UI changes, confusing flows, or non-code proof). If not needed, say so in the checklist.

## Screenshot (when helpful)

**Before fix:**

Found 28 errors in 5 files.
Errors  Files

2  src/app/modules/analysis/analysis.service.ts

23  src/app/modules/reaction/reaction.service.ts

1  src/app/modules/verify_email/verify_email.service.ts

1  src/config/razorpay.ts

1  src/utils/generation_timeout.ts

**After fix:**

npx tsc --noEmit → no errors for all 5 files

## What this PR does

Resolves unresolved merge conflicts in 5 backend files that caused 28 TypeScript
compilation errors, breaking the entire backend build. Each file had duplicate
imports, orphaned code fragments, or unclosed blocks left behind from bad merges.
Fixed by restoring clean function bodies and removing duplicate/orphaned code blocks.

## Type of change

Check all that apply (if more than one, explain in “What this PR does”).

- [ ] Bug fix

## Related issue

fixes #3081 

## Checklist

- [ ] I have added screenshots or a recording when they help explain this PR, or noted **N/A** with a one-line reason.
- [ ] I have filled in the related issue number when there is one.
- [ ] I have tested my changes.
- [ ] I have done a self-review of the code.

### CODE REVIEW

**Comment by rishita510** [comment]
The CI/typecheck failures are pre-existing TypeScript errors that exist on the 
main branch before this PR. All failing files are outside the scope of this fix:

- src/app/modules/auth/auth.service.ts
- src/app/modules/auth/auth.controller.ts
- src/app/modules/newsletter/newsletter.controller.ts
- src/app/modules/post/post.controller.ts
- src/app/modules/user/user.interface.ts

None of the 5 files fixed in this PR appear in the CI failure log. 
These errors can be verified on main independently of this PR.

**Comment by ronisarkarexe** [comment]
@rishita510 thanks for fix issue

**Comment by ronisarkarexe** [comment]
pls give a star
