### ISSUE TITLE
BUG: auth.service.ts has duplicate type declarations and duplicate getToken export causing TypeScript build failure

### ISSUE THREAD

**Issue by yatri28** [ronisarkarexe/ai-stories-book#1766]
### Is there an existing issue for this?
- [x] I have searched the existing issues

### What happened?
`frontend/src/services/auth.service.ts` contains several duplicate declarations that will cause TypeScript compilation errors:

1. `AuthUserInfo` type is declared **twice** — once as `export type AuthUserInfo` (line 10) and again as `type AuthUserInfo` (line 18) with a slightly different shape (the second one adds `avatar?`)
2. `buildUserInfo` function is defined **twice** (lines 34 and 44) with conflicting implementations
3. `export const getToken` is exported **twice** (lines 116 and 117)

This appears to be a bad merge where two versions of the file were concatenated instead of properly merged.

### Steps to reproduce
1. Clone the repo
2. `cd frontend && pnpm tsc --noEmit`
3. Observe: TypeScript errors — duplicate identifier `AuthUserInfo`, duplicate function `buildUserInfo`, duplicate export `getToken`

### Environment (if relevant)
File: `frontend/src/services/auth.service.ts`
Lines: 10 & 18 (type), 34 & 44 (function), 116 & 117 (export)

**Fix needed:** Remove the first (stale) copy of each declaration, keeping the more complete second version which includes `avatar?` and `_id` fallback in `buildUserInfo`.

- [x] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

**Comment by tanujkinkar9** [comment]
Hi @ronisarkarexe, I noticed this issue is currently assigned. If the current assignee is not actively working on it or if help is needed, I’d be happy to work on this under GSSoC'26.

I have already understood the fix: remove the duplicate `AuthUserInfo`, duplicate `buildUserInfo`, and duplicate `getToken` export while keeping the more complete version with `avatar?` and `_id` fallback.

Please assign it to me if available.
