### PR TITLE
fix(security): rate-limit bug report, contact and newsletter subscribe endpoints

### LINKED ISSUE #1656: BUG: Bug report, contact and newsletter subscribe endpoints have no rate limiting
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

Three unauthenticated POST endpoints have no rate limiting, so a single client can flood them.

- `POST /api/v1/bug-reports/submit` (`bug_report.router.ts`): anyone can insert unlimited bug report documents.
- `POST /api/v1/contact` (`contact.route.ts`): each request sends an email via SMTP, so flooding it both spams the support inbox and abuses the mail credentials.
- `POST /api/v1/newsletter/subscribe` (`newsletter.route.ts`): each request triggers a verification email via SMTP, same email-abuse and inbox-flood vector, and can be used to mail-bomb arbitrary addresses.

These endpoints are intentionally public (anonymous users can legitimately use them), so the fix is rate limiting rather than authentication.

This is different from #1043, which is about rate limiting the payment order endpoint specifically. The serverless-safe MongoDB-backed rate limiter added in #1519 / #1520 is already on `main`, so these endpoints can reuse it directly.

This maps to CWE-770 (Allocation of Resources Without Limits or Throttling).

### Steps to reproduce

1. Without authenticating, send many requests in a loop to any of the three endpoints, for example:
   ```
   for i in $(seq 1 50); do
     curl -s -o /dev/null -w "%{http_code}\n" -X POST \
       https://apistorysparkai.vercel.app/api/v1/newsletter/subscribe \
       -H "Content-Type: application/json" -d '{"email":"victim@example.com"}'
   done
   ```
2. Observe that none are throttled, and for contact/newsletter each accepted request sends an email.

### Environment (if relevant)

- Files: `bug_report.router.ts`, `contact.route.ts`, `newsletter.route.ts`

### Suggested fix

Mount the existing `createRateLimiter` factory (from `ip.rate-limiter.ts`, MongoDB-backed and serverless-safe) on each endpoint with its own key prefix: bug report 10 per hour, contact 5 per hour, newsletter subscribe 5 per hour. The email-sending endpoints get a tighter limit since they are the credential-abuse vector.

A PR is attached.

### Screenshots or screen recording (if helpful)

N/A. The loop above is sufficient proof.

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

### PR DESCRIPTION
**Pull request by Anexus5919**
## Screenshot (when helpful)

N/A. Backend middleware change. Verified via type check and a code trace, described below.

## What this PR does

Adds rate limiting to the three unauthenticated POST endpoints that were previously unthrottled, so a single client cannot flood them.

- `POST /api/v1/bug-reports/submit`: 10 per hour per IP.
- `POST /api/v1/contact`: 5 per hour per IP (each request sends an email).
- `POST /api/v1/newsletter/subscribe`: 5 per hour per IP (each request sends a verification email).

These endpoints are intentionally public, so the fix is rate limiting, not authentication. The email-sending endpoints get a tighter limit since they are the credential and inbox abuse vector.

### How

Reuses the existing MongoDB-backed `createRateLimiter` factory in `ip.rate-limiter.ts` (added in #1519 / #1520, serverless-safe across instances). Three new pre-configured limiters with their own key prefixes (`bug_report`, `contact`, `newsletter`) are added there and mounted as the first middleware on each route, ahead of validation.

## How I verified

1. Confirmed all three routes had no rate limiter before this change.
2. Confirmed the new limiters reuse the same factory and store as the existing auth and payment limiters, so they hold across serverless instances.
3. Ran `tsc` on the backend. With the unrelated pre-existing parse error in `review.service.ts` temporarily set aside, my four changed files type-check cleanly and introduce no new errors.

## Note for the maintainer

While verifying, `tsc` surfaced several pre-existing backend build errors unrelated to this PR: a parse error in `review.service.ts` (line 83), a `Cannot find name 'main'` artifact in `comment.service.ts` (line 46), unimported `validateRequest` / `PostValidator` in `post.router.ts` (line 64, fixed separately in #1649), and a `_id` type error in `recommendation.service.ts`. These break the backend build independently and are worth their own fixes.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update

## Related issue

Closes #1656

## More screenshots (optional)

N/A.

## Checklist

- [x] I have added screenshots or a recording when they help explain this PR, or noted **N/A** with a one-line reason.
- [x] I have filled in the related issue number when there is one.
- [x] I have tested my changes.
- [x] I have done a self-review of the code.

### CODE REVIEW

**Comment by Anexus5919** [comment]
@ronisarkarexe Kindly have a review on this pr. Thanks!
