### PR TITLE
fix(ci): regenerate pnpm-lock.yaml to match root package.json

### PR DESCRIPTION
**Pull request by vipul674**
## What this PR does

Resolves **two** structural CI failures in this repo:

### 1. `pnpm-lock.yaml` was missing two specifiers

The lockfile was missing two specifiers present in the root `package.json` dependencies:

- `@flaticon/flaticon-uicons ^3.3.1`
- `framer-motion ^12.40.0`

This made the **lint** workflow fail on `pnpm install --frozen-lockfile` with `ERR_PNPM_OUTDATED_LOCKFILE` because pnpm@9 refuses to install when the lockfile specifier set doesn't match the manifest specifier set.

**Fix**: re-run `pnpm install` locally to add the missing entries. Diff: `+27 / -2` lines, no package-graph change beyond adding the two missing direct dependencies.

### 2. `.github/workflows/main.yml` was an npm-based CI on a pnpm project

The "CI" workflow's single `build` job used `cache: npm`, `npm install`, and `npm run build`, but the project is a pnpm workspace with only `pnpm-lock.yaml` (no `package-lock.json` or `yarn.lock`). The build workflow therefore failed on every push with:

> Dependencies lock file is not found in /home/runner/work/story-spark-ai/story-spark-ai. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock

This was a long-standing misconfiguration that masked all other build errors — every PR on `main` had a red build badge purely because of this mismatch, regardless of what the PR actually changed.

**Fix**: rewrite `main.yml` to use `pnpm/action-setup@v2` with `pnpm@9.15.9`, `cache: pnpm`, and `pnpm install --frozen-lockfile`. Also adopt the same per-workspace change-detection pattern already used in `typecheck.yml` so a lockfile-only change (like this one) doesn't trigger a full backend rebuild. Per-workspace `pnpm --filter ... build` replaces the monolithic `npm run build`, matching the typecheck convention.

## Status of the other 3 issues originally documented in #1742

While this PR was being prepared, upstream merged three other commits that independently resolved the other issues called out in #1742:

| Originally documented | Resolved by | Notes |
|---|---|---|
| `backend/src/app.ts(23,9)` — TS2769 on `app.use(limiter)` | `2e5dad0` ("fix build after syncing with upstream main", Krish Patel) | `app.use(limiter as any)` |
| `backend/src/app/modules/comment/comment.service.ts(46,1)` — broken `getCommentsByPostId` body | `802f428` ("feat(auth): add refresh token rotation with reuse detection and logout") | Body now properly fetches + populates comments |
| `backend/src/app/modules/recommendation/recommendation.service.ts(58,58)` — `r._id` not on `IPost` | (residual: type no longer `IPost[]`, see commit 7fc7d23 "fix(backend): resolve typescript build errors and bad merges") | Resolved via interface/type refactor |

So this PR is the **only outstanding fix** from the original #1742 list.

## Out of scope (newly discovered, NOT in #1742)

`tsc` still reports two errors on `main` that **were not in #1742**:

```
src/app/modules/auth/auth.controller.ts(136,3): error TS1005: '}' expected.
src/app/modules/auth/auth.router.ts(52,1): error TS1128: Declaration or statement expected.
```

These are pre-existing in the most recent auth module refactor and appear to be stray lines from a botched merge. They're out of scope for this PR — happy to file a follow-up issue (and PR) for them if the maintainer wants, but I didn't want to expand the scope of #1742 unilaterally.

**Important**: thanks to the change-detection added to `main.yml`, a PR that only touches `pnpm-lock.yaml` (or any file outside `frontend/` and `backend/`, like `.github/workflows/*` itself) will skip the backend/frontend build steps, so these 2 errors no longer block this specific PR. They'll still be caught by `tsc` for any PR that actually touches backend source — which is the right place to surface them.

## CI status (this PR)

- ✅ `lint` — `pnpm install --frozen-lockfile` now passes
- ✅ `typecheck` — no backend/frontend changes, skipped correctly
- ✅ `build` — no backend/frontend changes, skipped correctly (the workflow change fixed the long-standing "lock file not found" failure)
- ✅ `greeting`, `label`, `validate` — all pass

## Files changed

- `pnpm-lock.yaml` (+27 / −2)
- `.github/workflows/main.yml` (+59 / −7) — full rewrite from npm to pnpm + change detection

## AI tool disclosure

LLM was used as a research/coordination assistant for the investigation and PR drafting. All commit content, decision-making, and verification was done by the human contributor.

### CODE REVIEW

**Comment by vipul674** [comment]
@ronisarkarexe The tracking issues have resolved, please review and merge the pr.

**Comment by ronisarkarexe** [comment]
Please give a star to support my project.
