### ISSUE TITLE
BUG: backend fails to compile on main: 30 TypeScript errors across 10 files (npm run build -w backend)

### ISSUE THREAD

**Issue by Doremon-tech-svg** [ronisarkarexe/ai-stories-book#3332]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

Running the backend's TypeScript build on a clean checkout of main fails with 30 compile errors across 10 files. This means npm run build -w backend (and likely the CI build step, if backend is included in it) is currently broken for everyone — not just for any specific PR or feature branch.

I confirmed this is pre-existing on main and unrelated to any of my local changes by running git stash to remove my own edits and re-running the build — the exact same 30 errors appeared in the exact same files/lines.

### 1. `src/app/modules/analysis/analysis.controller.ts:13`
```
error TS2554: Expected 1 arguments, but got 2.
const result = await AnalysisService.getDashboardAnalysis(userId as string, userRole as string);
```
The controller calls `getDashboardAnalysis` with 2 arguments, but the service function signature only accepts 1. Either the service signature needs to accept `userRole`, or the controller call needs to drop the extra argument — needs a maintainer/owner decision on which is the actual intended behavior.

### 2. `src/app/modules/auth/auth.service.ts:281` + `src/app/modules/user/user.interface.ts:25-28`
```
error TS2739: Type '{ facebook; twitter; linkedin; instagram }' is missing the following properties from type '{ facebook; twitter; linkedin; instagram; github; discord }': github, discord
```
```
error TS2300: Duplicate identifier 'github' / 'discord' (user.interface.ts lines 25-28)
```
These two are very likely linked: `user.interface.ts` appears to declare `github` and `discord` twice (possibly in two overlapping interface blocks, e.g. a `social` sub-interface defined or merged twice), and separately, `auth.service.ts` builds a `social` object literal missing `github`/`discord` entirely. This looks like a leftover from an incomplete social-links feature merge. Needs someone to check `user.interface.ts` around lines 20-30 and reconcile the duplicate fields, then update `auth.service.ts:281` to populate them.

### 3. `src/app/modules/newsletter/newsletter.controller.ts` (14 errors, lines 1-141)
```
error TS2300: Duplicate identifier 'Request' / 'Response' / 'newsletterService' / 'httpStatus'
error TS2451: Cannot redeclare block-scoped variable 'subscribe' / 'verify' / 'unsubscribeByToken'
```
The entire file content appears to be duplicated — the same imports (`Request`, `Response`, `newsletterService`, `httpStatus`) and the same three exported functions (`subscribe`, `verify`, `unsubscribeByToken`) are declared once around lines 1-69 and again around lines 71-141. This looks like an accidental copy-paste duplication of the whole file body (possibly from a bad merge). Fix should be to delete the duplicated second half of the file.

### 4. `src/app/modules/post/post.controller.ts:100` and `:113`
```
error TS2554: Expected 1 arguments, but got 2.
const result = await PostService.getSinglePost(id, token);
```
```
error TS2554: Expected 1-2 arguments, but got 3.
const result = await PostService.getPostsByTag(tag, excludeId, limit);
```
Both `getSinglePost` and `getPostsByTag` in `post.service.ts` are defined with fewer parameters than the controller is passing in. Either the service functions need to be updated to accept the extra params (`token` for permission-aware single-post fetches, `limit` for tag-based queries), or the controller calls need to be corrected. Worth checking if these controller calls are recent additions that the corresponding service update was never merged for.

### 5. `src/app/modules/verify_email/verify_email.router.ts:3`
```
error TS2305: Module '"./otp.rate-limiter.middleware"' has no exported member 'otpRateLimiter'.
```
The router imports `otpRateLimiter` from `otp.rate-limiter.middleware`, but that module doesn't export anything by that name (possibly a different export name, or the middleware was renamed/removed without updating this import).

### 6. `src/controllers/payment.controller.ts:4`
```
error TS2307: Cannot find module '../models/user.model' or its corresponding type declarations.
```
This import path doesn't resolve. Note this file lives under `src/controllers/`, separate from the `src/app/modules/user/` structure used elsewhere in the codebase — possibly a leftover from an older folder structure, or the import path should point to `src/app/modules/user/user.model` instead.

### 7. `src/routes/story.routes.ts:48`
```
error TS2551: Property 'aiFreeStoryContinuationMultiple' does not exist on type [...]. Did you mean 'aiFreeStoryContinuation'?
```
The route calls a method `aiFreeStoryContinuationMultiple` that doesn't exist on `AiModelService` — only the singular `aiFreeStoryContinuation` is defined. Either this route needs a new service method implemented, or it should call the existing singular method.

### 8. `src/socket/collab.socket.ts:165` and `:181`
```
error TS2552: Cannot find name 'rooms'. Did you mean 'room'?
```
Likely a simple typo — `rooms.get(roomId)` should probably be a different variable name (e.g. a module-level `rooms` Map that either doesn't exist or was renamed). Appears twice, so probably a single root cause (a missing/renamed `rooms` collection at the top of the file).

### 9. `src/utils/sanitize.util.ts:190, 192, 197`
```
error TS2862: Type 'T' is generic and can only be indexed for reading.
```
TypeScript strictness issue: the generic type `T` is being mutated (`result[key] = ...`) but TS only allows reading from a generic-indexed type, not writing. Needs either a type assertion/cast, or restructuring the function to build a new object instead of mutating the generic-typed `result` in place.

## Expected behavior
`npm run build -w backend` should compile cleanly with zero errors on `main`, so contributors and CI can rely on it as a real signal rather than a known-broken baseline.

## Additional notes
- I found this while testing an unrelated one-line fix for #3259. Confirmed via `git stash` that all 30 errors exist independently of that change.
- This may be several separate underlying bugs bundled by one build run; happy to split into smaller issues per file/area if a maintainer prefers that instead of one umbrella issue.
- Separately, `npm install` at the repo root also currently fails without `--legacy-peer-deps` due to a `vite-plugin-pwa` / `vite` v6 peer dependency mismatch in the frontend — let me know if that should be its own issue too.

/assign

### Steps to reproduce

1. Clone the repo fresh / check out main
2. npm install --legacy-peer-deps (see note below — there's also a peer dependency conflict on install, may be worth a separate issue)
3. npm run build -w backend
4. Observe 30 errors, build exits with code 2

### Environment (if relevant)

Backend: Node.js + TypeScript + MongoDB
Command: npm run build -w backend (runs tsc)

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue
